### ISSUE TITLE
Migrate to NestJS

### ISSUE THREAD

**Issue by manuel-rw** [manuel-rw/jellyfin-discord-music-bot#6]
# Current behavior

- Bot is unable to play music
- Code is not typed
- Old API is being used
- Code is messy and has barely any structure

# New behavior

- Migrated to Nest framework
- Code is completely typed
- New API is being used
- DI approach is being used

# Todo
- [x] Migrate to the NestJS Boilerplate
- [x] Write minimal implementation of Discord Client
- [x] Write minimal implementation of Jellyfin Client
- [x] Write command system
- [x] Write commands:
  - [x] Summon
  - [x] Help
  - [x] Play
  - [x] Disconnect
  - [x] Stop
  - [x] Status
  - [x] Current
  - [x] Pause
  - [x] Search
- [x] Write playlist manager
- [x] Write search function
- [ ] Report playback capabilities and report to Jellyfin Media Server
- [x] Use audio API of discord.js
- [x] Support albums and playlists
- [x] Code cleanup

**Comment by manuel-rw** [comment]
## Status Update

![image](https://user-images.githubusercontent.com/30572287/208212938-04a7b6dd-0cde-4d30-9404-b5400f67abe4.png)
![image](https://user-images.githubusercontent.com/30572287/208213058-93b35fe1-83ff-47f1-9f9c-b8b899fb4059.png)

**Comment by DX37** [comment]
How should I declare config settings? I'm not seeing any config.json, but app requires settings.

**Comment by manuel-rw** [comment]
Create a file named ``.env`` in the root directory with this content:
```env
DISCORD_CLIENT_TOKEN=
JELLYFIN_SERVER_ADDRESS=
JELLYFIN_AUTHENTICATION_USERNAME=
JELLYFIN_AUTHENTICATION_PASSWORD=
```

Enter the token, Jellyfin username, password and the server address.
Then, start the application again.

**Comment by manuel-rw** [comment]
**It's finally working!** 🚀 The stream builder is not the most elegant solution yet, but this is coming along very well.
@DX37 can you try to connect to your Jellyfin instance and check if /search <name> works for you?

PS: Note that you should not run this unsupervised, since there is currently a major security issue with /play.

**Comment by DX37** [comment]
Can't get it connected to Discord:
```
[Nest] 1681817  - 2022-12-17 11:04:34 PM     LOG [InstanceLoader] DiscordModule dependencies initialized +1ms
[Nest] 1681817  - 2022-12-17 11:04:34 PM     LOG [RoutesResolver] AppController {/}: +6ms
[Nest] 1681817  - 2022-12-17 11:04:34 PM     LOG [RouterExplorer] Mapped {/, GET} route +2ms
[Nest] 1681817  - 2022-12-17 11:04:34 PM     LOG [SearchItemCommand] Subscribe to event(on): interactionCreate
[Nest] 1681817  - 2022-12-17 11:04:34 PM   DEBUG [JellyfinService] Created Jellyfin Client and Api
(node:1681817) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 interactionCreate listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
[Nest] 1681817  - 2022-12-17 11:04:35 PM   DEBUG [JellyfinService] Connected using user '874db6e86e8a432b9fedd573c645f976'
[Nest] 1681817  - 2022-12-17 11:04:36 PM   ERROR [ClientService] Failed to connect to Discord API
[Nest] 1681817  - 2022-12-17 11:04:36 PM   ERROR [ClientService] Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
[Nest] 1681817  - 2022-12-17 11:04:36 PM     LOG [NestApplication] Nest application successfully started +4ms
```

**Comment by manuel-rw** [comment]
Seems like your bot application has insufficient permissions / intents. Can you maybe re-invite with higher permissions?
```
[Nest] 1681817  - 2022-12-17 11:04:36 PM   ERROR [ClientService] Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
```

Maybe you also need to enable this one:
![image](https://user-images.githubusercontent.com/30572287/208250979-f36261c7-5911-4071-bcaf-a100c953e22c.png)

**Comment by DX37** [comment]
Got it.
Can confirm, works through /search
![изображение](https://user-images.githubusercontent.com/12829428/208251422-d78deaed-8aa5-4fe7-8222-ea860e0b330c.png)

**Comment by manuel-rw** [comment]
Amazing! Thanks for confirming. I think I'll implement playlists now and do some code cleanup.
I'll let you know when there's something new you can try out

**Comment by DX37** [comment]
Look, sometimes it just crashes on some simple /search requests (maybe because they return 0 results):
```
[Nest] 1691861  - 2022-12-17 11:32:32 PM   DEBUG [JellyfinSearchService] Searching for 'good enough'
[Nest] 1691861  - 2022-12-17 11:32:32 PM   DEBUG [JellyfinSearchService] Found 2 results for 'good enough'
[Nest] 1691861  - 2022-12-17 11:32:36 PM   DEBUG [JellyfinStreamBuilderService] Attempting to build stream resource for item 4c30d074505bba993b169de3fcf0b1cc with bitrate 64000
[Nest] 1691861  - 2022-12-17 11:32:36 PM   DEBUG [DiscordVoiceService] state change:
from {"status":"playing","missedFrames":0,"playbackDuration":36360,"resource":true,"silencePacketsRemaining":3,"stepTimeout":false}
to {"status":"buffering","resource":true,"stepTimeout":false}
[Nest] 1691861  - 2022-12-17 11:32:36 PM   DEBUG [DiscordVoiceService] state change:
from {"status":"buffering","resource":true,"stepTimeout":false}
to {"status":"playing","missedFrames":0,"playbackDuration":0,"resource":true,"stepTimeout":false}
[Nest] 1691861  - 2022-12-17 11:32:47 PM   DEBUG [JellyfinSearchService] Searching for 'adhd'
[Nest] 1691861  - 2022-12-17 11:32:47 PM   DEBUG [JellyfinSearchService] Found 0 results for 'adhd'

/opt/containers/jellyfin-discord-music-bot/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:498
                                throw new DiscordAPIError(data, 'code' in data ? data.code : data.error, status, method, url, requestData);
          ^
DiscordAPIError[50035]: Invalid Form Body
data.components[0].components[0].options[BASE_TYPE_REQUIRED]: This field is required
    at SequentialHandler.runRequest (/opt/containers/jellyfin-discord-music-bot/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:498:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SequentialHandler.queueRequest (/opt/containers/jellyfin-discord-music-bot/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:198:11)
    at REST.request (/opt/containers/jellyfin-discord-music-bot/node_modules/@discordjs/rest/src/lib/REST.ts:343:20)
    at ChatInputCommandInteraction.reply (/opt/containers/jellyfin-discord-music-bot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5)
```

**Comment by DX37** [comment]
And if I'm doing `yarn`, it gives an error with jellyfin-apiclient and tells me to use `npm` instead
```
error jellyfin-apiclient@1.10.0: The engine "yarn" is incompatible with this module. Expected version "YARN NO LONGER USED - use npm instead.". Got "1.22.19"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
Which is fine, using `npm install` works good.

**Comment by manuel-rw** [comment]
> Look, sometimes it just crashes on some simple /search requests (maybe because they return 0 results):

I have noticed this too, but I hadn't had the time yet to investigate this. But thank you for reporting it! :)

> And if I'm doing yarn, it gives an error with jellyfin-apiclient and tells me to use npm instead

Yea, I forgot to remove the old Javascript API package. My new version with NestJS is using the newer Typescript SDK instead.

**Comment by manuel-rw** [comment]
@DX37 can you review again? I fixed a ton of issues, removed the ``/search`` (note: Discord might take some time to remove the command from your server. You'll have to wait) command, improved ``/play``, added ``/current`` (will be replaced by ``/playlist``) and finally added some proper playlist logic. Let me know what you think

**Comment by DX37** [comment]
@manuel-rw 
`/current` not working, nor listed in commands list. `/playlist` doing it's job, but I got a crash once, like 0 results crash above. Didn't crashed after that, at least.
Playlist logic works good, but maybe commands should be named with more sense, like  `/next` instead of `/skip` and `/add` instead of `/play` (maybe `/add` should add to playlist, but `/play` should add track to end of the playlist and start playing it immediately). And probably instead of long ass `/previous`, but that's just my candy eye stuff.

When searching for track by it's name, it didn't write artists of tracks.

![изображение](https://user-images.githubusercontent.com/12829428/208283085-301bfac8-cadd-487a-9e6a-a4a1ed2a4b21.png)

Choosing to play a playlist crashes bot.

![изображение](https://user-images.githubusercontent.com/12829428/208283256-d66e10fb-f900-427c-85f0-92eab3973481.png)
Like this:
```
[Nest] 1981655  - 2022-12-18 12:37:32 PM   DEBUG [JellyfinStreamBuilderService] Attempting to build stream resource for item 144cda263ea5704670a9010560b974b8 with bitrate 64000

/opt/containers/jellyfin-discord-music-bot/node_modules/date-fns/intervalToDuration/index.js:57
  if (isNaN(start.getTime())) throw new RangeError('Start Date is invalid');
                                    ^
RangeError: Start Date is invalid
    at intervalToDuration (/opt/containers/jellyfin-discord-music-bot/node_modules/date-fns/intervalToDuration/index.js:57:37)
    at PlayItemCommand.onStringSelect (/opt/containers/jellyfin-discord-music-bot/src/commands/play.comands.ts:185:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by manuel-rw** [comment]
>  /current not working, nor listed in commands list. /playlist doing it's job, but I got a crash once, like 0 results crash above. Didn't crashed after that, at least.

``/current`` was the old version of ``/playlist``. Sometimes Discord decides to not remove commands from the selection menu.
About the crash: Never happened to me before. Do you have the stack trace?

>  Playlist logic works good, but maybe commands should be named with more sense, like /next instead of /skip and /add instead of /play (maybe /add should add to playlist, but /play should add track to end of the playlist and start playing it immediately). And probably instead of long ass /previous, but that's just my candy eye stuff.

Renaming ``/skip`` to ``/next`` sure makes sense. Although I think that ``/previous`` should stay, because it's the opposite of the word "next".

**What do you think of this idea:**
I'll add a parameter to ``/play``, which can modify the add behavior.
``enqueue`` -> Add it at the end of the playlist (default)
``next`` -> Add it after the currently active track
``immediate`` -> Add it at the end of the playlist and immediately skip to this track

> When searching for track by it's name, it didn't write artists of tracks. 

Ok, I'll add the artist(-s) too there!

> Choosing to play a playlist crashes bot.

Yes, I know that. Although you can currently select playlists and albums, it will simply crash.
What do you think should be the default behavior here?

**Option 1**: Iterate through tracks in playlist or album and add them to the current playlist
**Option 2**: Replace the current playlist with the entire playlist or album



I think that I'll merge this soon, since there is not a lot missing anymore compared to https://github.com/KGT1/jellyfin-discord-music-bot base upstream repository.

Personally, I still miss a few features (like repeat mode, shuffle, instant mix, display of playback progress, ....), but those are not part of this MVP.

**Comment by DX37** [comment]
Oh god, I missed words again.
I meant change long `/previous` to `/prev`.

> I'll add a parameter to `/play`, which can modify the add behavior.

I think there should be separate commands, instead of modifications. So user will know which command to use directly to do what it supposed to do. Setting modifications all time, when you need some behavior sometimes, will not look comfortable.



> What do you think should be the default behavior here?
I guess Option 2 is good. User can create his own playlist in Jellyfin, and choose it trough bot. Simple enough starting of music.

**Comment by manuel-rw** [comment]
Okay, thank you for your feedback. I think that I'll merge this soon to my master branch.
I think the MVP has almost been reached and that we should implement other commands afterwards.
There is also still the need for a Container image, which I will create later.
